### ISSUE TITLE
add installation instructions for Parrot OS 

### ISSUE THREAD

**Issue by suchoudh** [open-pomodoro/openpomodoro-cli#20]

**Comment by pjboro** [comment]
Just learned about the existance of one more Linux distribution. If it works like most distributions (and it probably does), then

>User-specific executable files may be stored in $HOME/.local/bin. Distributions should ensure this directory shows up in the UNIX $PATH environment variable, at an appropriate place. 

[source](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

So, you download the file, move it to `~/.local/bin`, run `chmod u+x` on it to make it executable. If this dir doesn't show up in `echo $PATH`, then add `export PATH="$HOME/.local/bin"` to your `$HOME/.bashrc`, `$HOME/.zshrc` or your shell's analog.

Regards!
