### ISSUE TITLE
pomodoro goals and scope 

### ISSUE THREAD

**Issue by mksantos2** [open-pomodoro/openpomodoro-cli#22]
Hi. i was wondering if there's any way to set goals from a config file or even a tutorial to create a config file to setup the breaks and session's duration. thx

**Comment by justincampbell** [comment]
Yes! If you create `~/.pomodoro/settings` with the following contents, it will use these for goals/default duration:

```
daily_goal=8
default_pomodoro_duration=25
default_break_duration=5
```

These are defined in https://github.com/open-pomodoro/go-openpomodoro/blob/master/settings.go

I thought these were in the README, but apparently not. I would also love to add a `pomodoro init` command to install this with all of the current defaults.

**Comment by celsobenedetti** [comment]
> Yes! If you create `~/.pomodoro/settings` with the following contents, it will use these for goals/default duration:
> 
> ```
> daily_goal=8
> default_pomodoro_duration=25
> default_break_duration=5
> ```
> 
> These are defined in https://github.com/open-pomodoro/go-openpomodoro/blob/master/settings.go
> 
> I thought these were in the README, but apparently not. I would also love to add a `pomodoro init` command to install this with all of the current defaults.

this would be welcome in the README

**Comment by justincampbell** [comment]
@celsobenedetti I did this in https://github.com/open-pomodoro/openpomodoro-cli/pull/34 and forgot to merge it, sorry! It's there now.
