### ISSUE TITLE
configure where the data is saved

### ISSUE THREAD

**Issue by gedw99** [open-pomodoro/openpomodoro-cli#25]
i have a use case where i want to be able to save the data in a local github repo.

We could make it a setting in the config of  ~/.pomodoro/settings ?

**Comment by pjboro** [comment]
The project [doesn't seem to be maintained ](https://github.com/open-pomodoro/open-pomodoro-format/graphs/code-frequency), but on unix/linux-like you can move the original ~/.pomodoro/ dir to some different location and create a symlink in its place, linking to the location you moved the directory to. The app doesn't seem to care.

```text
mv ~/.pomodoro ~/.pomodoro_backup  # move your current data somewhere else for tests
mkdir /tmp/local-github-repo/
ln -s /tmp/local-github-repo/ $HOME/.pomodoro
ls -l ~/.pomodoro/  # we can see in ls output, that this file is a symlink to another dir
pomodoro start "some activity" -t test # let's run pomodoro as usual
pomodoro finish
echo some-entry > ~/.pomodoro/some-file  # creating one more file, just to illustrate
tail -n+1 /tmp/local-github-repo/* # print contents of all files in a dir
tail -n+1 ~/.pomodoro/*
```

https://man7.org/linux/man-pages/man1/ln.1.html
https://tldr.inbrowser.app/pages/common/ln

I hope that solves your problem :) Regards!

**Comment by pataquets** [comment]
> The project [doesn't seem to be maintained ](https://github.com/open-pomodoro/open-pomodoro-format/graphs/code-frequency),[...]

@justincampbell ping. any feedback? no obligation, just setting expectations, e.g. are you looking for [new/co-]maintainer(s)? thinking into opening it for adoption?

**Comment by justincampbell** [comment]
@pataquets I'm not actively using this, as my current development workflow requires multiple remote SSH sessions, and I haven't gotten around to solving for that. However, I'm happy to help review any changes that are submitted, or adding collaborators to this repo who are interested in helping maintain it.

**Comment by pataquets** [comment]
Thanks for the quick response, @justincampbell. I've opened #26 to help channel anything related. Hint: you might want to pin it for visibility.

**Comment by pjboro-identt** [comment]
@justincampbell @pataquets I appreciate your swift reaction - thank you :)

**Comment by pjboro** [comment]
I do appreciate your swift response, guys - thank you :)
