### ISSUE TITLE
[INFO] Maintenance status / help welcome

### ISSUE THREAD

**Issue by pataquets** [open-pomodoro/openpomodoro-cli#26]
First and foremost, I'd like to thank @justincampbell for his work and for sharing it. I find the idea of an [Open Pomodoro Format](https://github.com/open-pomodoro/open-pomodoro-format) very interesting and worth it.
This issue is meant for those interested in the software status and also in collecting feedback from potential interested third parties.

Quoting the maintainer's response on [issue #25](https://github.com/open-pomodoro/openpomodoro-cli/issues/25#issuecomment-1904333508):
> I'm not actively using this, as my current development workflow requires multiple remote SSH sessions, and I haven't gotten around to solving for that. However, I'm happy to help review any changes that are submitted, or adding collaborators to this repo who are interested in helping maintain it.

**Comment by justincampbell** [comment]
I don't believe this post is necessary. Anyone is free to make a contribution at any time, and that capability has not changed. I appreciate you bringing attention to it though.

**Comment by pataquets** [comment]
Glad to know it, @justincampbell. Thank you very much for your quick feedback.
