### ISSUE TITLE
Feature request: rename current pomodoro

### ISSUE THREAD

**Issue by alisdair** [open-pomodoro/openpomodoro-cli#6]
I find myself often misnaming pomodoros, and manually editing the history file. It might be nice to be able to rename the current pomodoro from the CLI instead.

**Comment by justincampbell** [comment]
Nice! I too was wondering if there should be an `amend` subcommand, which would take the same arguments as `start` but not restart the Pomodoro, only amend whatever was passed in.

```sh
$ pomodoro start "Good Morningg"  --tags work
25:00
Good Morningg
work
# 30s later...
$ pomodoro amend "Good Morning"
24:30
Good Morning
work
```

**Comment by justincampbell** [comment]
Done! #8
